### PR TITLE
feat: missing config is not an error

### PR DESCRIPTION
**Pull request by bfraterman-tkhsecurity**
This helps to have an optionally enabled hosted zone, for example a
production stage with hosted zone and a testing stage without a hosted
zone

### CODE REVIEW

**Review by miguel-a-calles-mba — CHANGES_REQUESTED** [review]
@bfraterman-tkhsecurity, thanks for the PR. I think the custom config should have a `required` option that can be set to `false`.

**Comment by miguel-a-calles-mba** [comment]
@bfraterman-tkhsecurity , are you able to share a sanitized extract of your `serverless.yml` file? I want to check whether having a `required: false` option makes sense.

**Comment by bfraterman-tkhsecurity** [comment]
@miguel-a-calles-mba we're using this conditional logic in our serverless file to only have a hostedzone deployed when deploying a dev or demo stack. We don't want to configure anything else if we want to deploy another stage, so our CI systems are able to choose random names for a stack (for automatic testing purposes) without having to alter any files or configuration in serverless.

serverless.yml
```
custom:
  # Set `hostedZone` when deploying to `dev` or `demo`
  hosted_zone_file_options:
    dev: serverless.hosted-zone.yml
    demo: serverless.hosted-zone.yml
  hostedZone: ${file(${self:custom.hosted_zone_file_options.${self:provider.stage}, "file-does-not-exist.yml"}), ""}
```

serverless.hosted-zone.yml:
```
name: ${self:custom.custom_domain}.
```

In this PR I've sort of reused the approach they have in the `serverless-certificate-creator` plugin.

**Comment by miguel-a-calles-mba** [comment]
@bfraterman-tkhsecurity, I think your approach is fine. I updated the code to clarify that the plugin is being skipped instead of it being disabled. I think that will be clearer in the new Serverless V3 logging.

May you test the PR in your CI at your convenience please?

```
npm i miguel-a-calles-mba/serverless-hosted-zone#pull/57
```

**Comment by bfraterman-tkhsecurity** [comment]
@miguel-a-calles-mba Tested the PR and seems to work fine for our scenarios!

Thanks a lot for your quick response!

**Review by miguel-a-calles-mba — APPROVED** [review]

**Pull request merged**
